---
apiVersion: v1
kind: Service
metadata:
  name: simple-public-lb
spec:
  type: LoadBalancer
  loadBalancerIP: ""
  selector:
    app: nginx
    microservice: simple
  ports:
  - protocol: TCP
    port: 80
    targetPort: web
