version: '3'

services:
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.105.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
      - logs:/var/log:ro
    environment:
      - GOOGLE_CLOUD_QUOTA_PROJECT
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT?}
volumes:
  logs:
